export const TRY_TO_SIGN_IN = "TRY_TO_SIGN_IN";
export const SUCCEDED_TO_SIGN_IN = "SUCCEDED_TO_SIGN_IN";
export const FAILED_TO_SIGN_IN = "FAILED_TO_SIGN_IN";

export const TRY_TO_SIGN_OUT = "TRY_TO_SIGN_OUT";
export const SUCCEDED_TO_SIGN_OUT = "SUCCEDED_TO_SIGN_OUT";
export const FAILED_TO_SIGN_OUT = "FAILED_TO_SIGN_OUT";

export const TRY_TO_CREATE_ROOM = "TRY_TO_CREATE_ROOM";
export const SUCCEDED_TO_CREATE_ROOM = "SUCCEDED_TO_CREATE_ROOM";
export const FAILED_TO_CREATE_ROOM = "FAILED_TO_CREATE_ROOM";
