/**
 * Sign in action types.
 */
export const TRY_TO_SIGN_IN = "TRY_TO_SIGN_IN";
export const SUCCEDED_TO_SIGN_IN = "SUCCEDED_TO_SIGN_IN";
export const FAILED_TO_SIGN_IN = "FAILED_TO_SIGN_IN";

/**
 * Sign out action types.
 */
export const TRY_TO_SIGN_OUT = "TRY_TO_SIGN_OUT";
export const SUCCEDED_TO_SIGN_OUT = "SUCCEDED_TO_SIGN_OUT";
export const FAILED_TO_SIGN_OUT = "FAILED_TO_SIGN_OUT";

/**
 * Room creation action types.
 */
export const TRY_TO_CREATE_ROOM = "TRY_TO_CREATE_ROOM";
export const SUCCEDED_TO_CREATE_ROOM = "SUCCEDED_TO_CREATE_ROOM";
export const FAILED_TO_CREATE_ROOM = "FAILED_TO_CREATE_ROOM";

/**
 * Messaging action types.
 */
export const TRY_TO_SEND_MESSAGE = "TRY_TO_SEND_MESSAGE";
export const SUCCEDED_TO_SEND_MESSAGE = "SUCCEDED_TO_SEND_MESSAGE";
export const FAILED_TO_SEND_MESSAGE = "FAILED_TO_SEND_MESSAGE";

/**
 * Room member action types.
 */
export const TRY_TO_ADD_ROOM_MEMBER = "TRY_TO_ADD_ROOM_MEMBER";
export const SUCCEDED_TO_ADD_ROOM_MEMBER = "SUCCEDED_TO_ADD_ROOM_MEMBER";
export const FAILED_TO_ADD_ROOM_MEMBER = "FAILED_TO_ADD_ROOM_MEMBER";

export const TRY_TO_REMOVE_ROOM_MEMBER = "TRY_TO_REMOVE_ROOM_MEMBER";
export const SUCCEDED_TO_REMOVE_ROOM_MEMBER = "SUCCEDED_TO_REMOVE_ROOM_MEMBER";
export const FAILED_TO_REMOVE_ROOM_MEMBER = "FAILED_TO_REMOVE_ROOM_MEMBER";
